# Desactivar lazy-initialization para asegurar la ejecución de DataSeeder y Beans al arrancar
spring.main.lazy-initialization=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Usar 'update' por defecto si la variable no está en Render para que cree/actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.h2.console.enabled=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never